// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meus Descontos Online - Todos os Melhores Descontos em um só Lugar",
  description: "Encontre as melhores promoções e descontos do Mercado Livre, Amazon, Magazine Luiza, Americanas, Shopee e AliExpress. Ofertas exclusivas para você economizar!",
  keywords: "descontos, promoções, ofertas, Amazon, Mercado Livre, Magazine Luiza, Americanas, Shopee, AliExpress, compras online, economia",
  authors: [{ name: "Meus Descontos Online" }],
  creator: "Meus Descontos Online",
  publisher: "Meus Descontos Online",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://meusdescontosonline.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: "Meus Descontos Online - Todos os Melhores Descontos em um só Lugar",
    description: "Encontre as melhores promoções e descontos do Mercado Livre, Amazon, Magazine Luiza, Americanas, Shopee e AliExpress.",
    url: 'https://meusdescontosonline.com',
    siteName: 'Meus Descontos Online',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Meus Descontos Online - Melhores Ofertas',
      },
    ],
    locale: 'pt_BR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: "Meus Descontos Online - Todos os Melhores Descontos em um só Lugar",
    description: "Encontre as melhores promoções e descontos dos principais marketplaces.",
    images: ['/og-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'seu-codigo-google-search-console',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://images.unsplash.com" />
        <meta name="theme-color" content="#0d6efd" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Meus Descontos" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        {children}
        <Script
          id="structured-data"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "Meus Descontos Online",
              "description": "Encontre as melhores promoções e descontos dos principais marketplaces",
              "url": "https://meusdescontosonline.com",
              "potentialAction": {
                "@type": "SearchAction",
                "target": "https://meusdescontosonline.com/?q={search_term_string}",
                "query-input": "required name=search_term_string"
              }
            })
          }}
        />
      </body>
    </html>
  );
}